- name: Install httpie
  homebrew:
    name: httpie
    state: latest
    update_homebrew: yes

- name: Install httpie plugins
  pip:
    name: '{{ item }}'
    state: latest
  with_items:
    - httpie-jwt-auth
    - http-prompt
