---
- name: Provision my MacBook
  hosts: all
  connection: local
  roles:
    - role: cask
      tags: [cask]
    - role: brew
      tags: [brew]
    - role: atom
      tags: [atom]
    - role: mas
      tags: [mas]
    - role: dotfiles
      tags: [dotfiles]
    - role: macos
      tags: [macos]
    - role: user
      tags: [user]
