- name: Install dotfiles
  copy:
    src: '{{ item }}'
    dest: ~/
  with_items:
    - .aliases
    - .bash_profile
    - .bash_prompt
    - .bashrc
    - .editorconfig
    - .exports
    - .gitignore
    - .gitconfig
