- name: Tap Homebrew repositories
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items:
    - homebrew/dupes
    - homebrew/versions
    - homebrew/php

- name: Ensure Java is present
  homebrew_cask:
    name: java
    state: present
    update_homebrew: yes

- name: Install Homebrew packages
  homebrew:
    name: '{{ item }}'
    state: latest
    update_homebrew: yes
  with_items:
    - ant
    - awscli
    - coreutils
    - findutils
    - git
    - go
    - httpie
    - jq
    - homebrew/php/php71
    - homebrew/php/php71-mcrypt
    - homebrew/php/composer
    - homebrew/php/box
    - tree
    - vault    
    - watch
    - wget

- name: Upgrade all homebrew packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  changed_when: false
