- name: Install docker cask
  homebrew_cask:
    name: '{{ item }}'
    state: present
    update_homebrew: yes
  with_items:
    - docker

- name: Install docker related brew packages
  homebrew:
    name: '{{ item }}'
    state: latest
    update_homebrew: yes
  with_items:
    - docker-clean
    - docker-completion
    - docker-compose-completion
