- name: Tap cask repository
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items:
    - caskroom/cask

- name: Ensure Java is present
  homebrew_cask:
    name: java
    state: present
    update_homebrew: yes

- name: Install Homebrew casks
  homebrew_cask:
    name: '{{ item }}'
    state: present
    update_homebrew: yes
  with_items:
    - aerial
    - atom
    - caffeine
    - docker
    - dropbox
    - franz
    - gas-mask
    - github-desktop
    - google-chrome
    - google-drive
    - iterm2
    - keepassx
    - phpstorm
    - postman
    - sequel-pro
    - spotify
    - tunnelblick
