- name: Tap cask repository
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items:
    - caskroom/cask

- name: Ensure Java is present
  homebrew_cask:
    name: java
    state: present
    update_homebrew: yes

- name: Install Homebrew casks
  homebrew_cask:
    name: '{{ item }}'
    state: present
    update_homebrew: yes
  with_items:
    - alfred
    - adobe-acrobat-reader
    - airdroid
    - aerial
    - atom
    - caffeine
    - calibre
    - dropbox
    - firefox
    - franz
    - gas-mask
    - github-desktop
    - google-chrome
    - google-drive
    - gpgtools
    - jetbrains-toolbox
    - iterm2
    - keepassx
    - keybase
    - mattermost
    - mountain-duck
    - mysqlworkbench
    - pgadmin4
    - phpstorm
    - postman
    - sequel-pro
    - spectacle
    - spotify
    - sublime-text
    - tunnelblick
    - virtualbox
    - vlc
